version: '2'

services:
 php:
    #image: php:fpm-alpine
    build: 
       context: .
       dockerfile: ./docker/php/Dockerfile
    # create and attach volume with website data
    volumes:
#        - ./data:/data
        - ./docker/php.ini:/usr/local/etc/php-fpm.d/php.ini

    mem_limit: 134217728
    cpu_shares: 10

 nginx:
    image: nginx:stable-alpine
    ports:
        - "8181:80"

    # create and attach volume with website data and config files
    volumes:
        - ./data:/data
        - ./docker/default.conf:/etc/nginx/conf.d/default.conf

    mem_limit: 134217728
    cpu_shares: 10

    # link php with nginx
    links:
        - php

